# -*- coding: utf-8 -*-
"""housing data set

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZBaL_j8b4qbwqJZQxb2WMSZVp-PlJRN6
"""

import pandas as pd
import matplotlib.pyplot as plt

!pip install autoviz

df = pd.read_csv('/content/housing dataset.csv')
df

df.head()

from autoviz.AutoViz_Class import AutoViz_Class
AV = AutoViz_Class()

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline
filename = "/content/housing dataset.csv"
sep=','
df = AV.AutoViz(
    filename
)